:WHERE_LOV AND (codigo_situacion = 'A' ) AND codigo_bloqueo_pedidos = 'N' AND para_venta = 'S' AND  (:b1.oc_orientada_a NOT IN ('A','T','F') OR ((:b1.oc_orientada_a = 'A' AND EXISTS (SELECT 1 FROM relacion_comer_almac r WHERE r.codigo_almacen = :b1.almacen_entrega AND codigo_org_comer = :b1.organizacion_comercial AND codigo_empresa = :global.codigo_empresa)) OR (:b1.oc_orientada_a = 'T' AND EXISTS (SELECT 1 FROM relacion_comer_almac r WHERE r.codigo_familia = articulos.codigo_familia AND codigo_org_comer = :b1.organizacion_comercial AND codigo_almacen = :b1.almacen_entrega AND codigo_empresa = :global.codigo_empresa)) OR (:b1.oc_orientada_a = 'F' AND EXISTS (SELECT 1 FROM relacion_comer_almac r WHERE r.codigo_familia = articulos.codigo_familia AND codigo_org_comer = :b1.organizacion_comercial AND codigo_empresa = :global.codigo_empresa)))) AND EXISTS (SELECT 1 FROM cadena_logistica cl WHERE cl.codigo_empresa = :global.codigo_empresa AND cl.codigo_articulo = articulos.codigo_articulo) AND (:b8.int_partida IS NULL OR EXISTS (SELECT 1 FROM historico_lotes hl WHERE hl.codigo_articulo = articulos.codigo_articulo AND hl.numero_lote_int = :b8.int_partida AND hl.codigo_empresa = :global.codigo_empresa AND HL.CANTIDAD_UNIDAD1>0)) AND (:b8.gran_lote IS NULL OR EXISTS (SELECT 1 FROM historico_lotes hl WHERE hl.codigo_articulo = articulos.codigo_articulo AND hl.descripcion_lote2 = :b8.gran_lote AND hl.codigo_empresa = :global.codigo_empresa)) and not exists (select 1 from almacenes_articulos aa where aa.codigo_empresa = articulos.codigo_empresa
   and aa.codigo_almacen = :b1.almacen_entrega and aa.codigo_articulo = articulos.codigo_articulo
   and aa.bloqueo_ventas = 'S')  AND ((:B1.TIPO_PEDIDO IN ('10','11','16','22','23A','23E','23J','23O','29','30','40','43','44','45','46','49','49A', '51') AND CODIGO_ESTAD6 IN ('PT')) OR
   (:B1.TIPO_PEDIDO IN ('23C','23K','23A','29A','23J') AND CODIGO_ESTAD6 IN ('MM')) OR
   (:B1.TIPO_PEDIDO IN ('23B','29','29A') AND CODIGO_ESTAD6 ='LI') OR
   (:B1.TIPO_PEDIDO IN ('22','29','23F','23G','23I') AND CODIGO_ESTAD6 IN ('ME','PE', 'MP'))  or
 (:B1.TIPO_PEDIDO IN ('12','23M') AND CODIGO_ESTAD6 IN ('PT') and articulos.codigo_articulo in  (select s.codigo_articulo from STOCKS_DETALLADO S where S.codigo_empresa=:global.codigo_empresa and S.codigo_almacen=:b1.almacen_entrega and S.codigo_zona=460 AND S.codigo_articulo=articulos.codigo_articulo)) or
 (:B1.TIPO_PEDIDO IN ('11','13','23N') AND CODIGO_ESTAD6 IN ('PT') and articulos.codigo_articulo in  (select s.codigo_articulo from STOCKS_DETALLADO S where S.codigo_empresa=:global.codigo_empresa and S.codigo_almacen=:b1.almacen_entrega and S.codigo_zona=111 AND S.codigo_articulo=articulos.codigo_articulo)) or (:B1.TIPO_PEDIDO IN ('15') AND CODIGO_ESTAD6 IN ('PT') and articulos.codigo_articulo in  (select s.codigo_articulo from STOCKS_DETALLADO S where S.codigo_empresa=:global.codigo_empresa and S.codigo_almacen=:b1.almacen_entrega and S.codigo_zona=200 AND S.codigo_articulo=articulos.codigo_articulo))
)


:WHERE_LOV AND (codigo_situacion = 'A' ) AND codigo_bloqueo_pedidos = 'N' AND para_venta = 'S' AND  (:b1.oc_orientada_a NOT IN ('A','T','F') OR ((:b1.oc_orientada_a = 'A' AND EXISTS (SELECT 1 FROM relacion_comer_almac r WHERE r.codigo_almacen = :b1.almacen_entrega AND codigo_org_comer = :b1.organizacion_comercial AND codigo_empresa = :global.codigo_empresa)) OR (:b1.oc_orientada_a = 'T' AND EXISTS (SELECT 1 FROM relacion_comer_almac r WHERE r.codigo_familia = articulos.codigo_familia AND codigo_org_comer = :b1.organizacion_comercial AND codigo_almacen = :b1.almacen_entrega AND codigo_empresa = :global.codigo_empresa)) OR (:b1.oc_orientada_a = 'F' AND EXISTS (SELECT 1 FROM relacion_comer_almac r WHERE r.codigo_familia = articulos.codigo_familia AND codigo_org_comer = :b1.organizacion_comercial AND codigo_empresa = :global.codigo_empresa)))) AND EXISTS (SELECT 1 FROM cadena_logistica cl WHERE cl.codigo_empresa = :global.codigo_empresa AND cl.codigo_articulo = articulos.codigo_articulo) AND (:b8.int_partida IS NULL OR EXISTS (SELECT 1 FROM historico_lotes hl WHERE hl.codigo_articulo = articulos.codigo_articulo AND hl.numero_lote_int = :b8.int_partida AND hl.codigo_empresa = :global.codigo_empresa AND HL.CANTIDAD_UNIDAD1>0)) AND (:b8.gran_lote IS NULL OR EXISTS (SELECT 1 FROM historico_lotes hl WHERE hl.codigo_articulo = articulos.codigo_articulo AND hl.descripcion_lote2 = :b8.gran_lote AND hl.codigo_empresa = :global.codigo_empresa)) and not exists (select 1 from almacenes_articulos aa where aa.codigo_empresa = articulos.codigo_empresa
   and aa.codigo_almacen = :b1.almacen_entrega and aa.codigo_articulo = articulos.codigo_articulo
   and aa.bloqueo_ventas = 'S')  AND ((:B1.TIPO_PEDIDO IN ('10','11','16','22','23A','23E','23J','23O','29','30','40','43','44','45','46','49','49A', '51') AND CODIGO_ESTAD6 IN ('PT')) OR
   (:B1.TIPO_PEDIDO IN ('23C','23K','23A','29A','23J') AND CODIGO_ESTAD6 IN ('MM')) OR
   (:B1.TIPO_PEDIDO IN ('23B','29','29A') AND CODIGO_ESTAD6 ='LI') OR
   (:B1.TIPO_PEDIDO IN ('22','29','23F','23G','23I') AND CODIGO_ESTAD6 IN ('ME','PE', 'MP'))  or
 (:B1.TIPO_PEDIDO IN ('12','23M') AND CODIGO_ESTAD6 IN ('PT') and articulos.codigo_articulo in  (select s.codigo_articulo from STOCKS_DETALLADO S where S.codigo_empresa=:global.codigo_empresa and S.codigo_almacen=:b1.almacen_entrega and S.codigo_zona=460 AND S.codigo_articulo=articulos.codigo_articulo)) or
 (:B1.TIPO_PEDIDO IN ('11','13','23N') AND CODIGO_ESTAD6 IN ('PT') and articulos.codigo_articulo in  (select s.codigo_articulo from STOCKS_DETALLADO S where S.codigo_empresa=:global.codigo_empresa and S.codigo_almacen=:b1.almacen_entrega and S.codigo_zona=111 AND S.codigo_articulo=articulos.codigo_articulo)) (:B1.TIPO_PEDIDO IN ('15') AND CODIGO_ESTAD6 IN ('PT') and articulos.codigo_articulo in  (select s.codigo_articulo from STOCKS_DETALLADO S where S.codigo_empresa=:global.codigo_empresa and S.codigo_almacen=:b1.almacen_entrega and S.codigo_zona=200 AND S.codigo_articulo=articulos.codigo_articulo))
)