CREATE OR REPLACE FORCE VIEW COBRANZA_PRM_BOL(CODIGO_RAPIDO, NOMBRE, RAZON_SOCIAL, TIPO_ENTIDAD, NIF, DIRECCION, FORMA_COBRO_PAGO, TIPO_CLIENTE, FECHA_BAJA, ESTADO, EMPRESA, DOCUMENTO, CONCEPTO, FECHA_FACTURA, FECHA_VENCIMIENTO, FECHA_ASIENTO, DOCUMENTO_VIVO, 
IMPORTE, IMPORTE_SUSTITUIDO, IMPORTE_COBRADO) AS
SELECT C.CODIGO_RAPIDO,
       C.NOMBRE,
       C.RAZON_SOCIAL,
       C.TIPO_ENTIDAD,
       C.NIF,
       C.DIRECCION,
       C.FORMA_COBRO_PAGO,
       C.TIPO_CLIENTE,
       C.FECHA_BAJA,
       HC.ESTADO,
       HC.EMPRESA,
       HC.DOCUMENTO,
       HC.CONCEPTO,
       HC.FECHA_FACTURA,
       HC.FECHA_VENCIMIENTO,
       HC.FECHA_ASIENTO,
       HC.DOCUMENTO_VIVO,
       HC.IMPORTE,
       HC.IMPORTE_SUSTITUIDO,
       HC.IMPORTE_COBRADO
FROM HISTORICO_COBROS HC,
     CLIENTES C
WHERE HC.CODIGO_CLIENTE = C.CODIGO_RAPIDO
  AND C.FECHA_BAJA IS NULL
  AND HC.EMPRESA = C.CODIGO_EMPRESA
  AND HC.DOCUMENTO_VIVO = 'S'
  AND HC.STATUS_IMPAGADO IN ('N', 'S', 'D', 'P', 'A', 'F')
  AND HC.SITUACION_APUNTE = 'D'
  AND NVL(HC.FACTORING, 'N') IN ('N', DECODE('S', 'S', 'A', 'N'), DECODE('N', 'S', 'F', 'N'))
  AND HC.EMPRESA = '004'
  AND HC.CODIGO_CLIENTE IN (SELECT CODIGO_RAPIDO FROM CLIENTES WHERE EMPRESA = '004' AND FECHA_BAJA IS NULL)
  and hc.FECHA_FACTURA =to_Date('05/05/2025','DD/MM/YYYY')


/****************************************************************************************************/
  /* CMAPOS QUE FALTAN:
  REGION
  STATUS DEL PAGO
  */

CREATE OR REPLACE FORCE VIEW COBRANZA_PRM_BOL(CODIGO_RAPIDO, NOMBRE, RAZON_SOCIAL, TIPO_ENTIDAD, NIF, DIRECCION, FORMA_COBRO_PAGO, TIPO_CLIENTE, FECHA_BAJA, ESTADO, EMPRESA, DOCUMENTO, CONCEPTO, FECHA_FACTURA, FECHA_VENCIMIENTO, FECHA_ASIENTO, DOCUMENTO_VIVO, 
IMPORTE, IMPORTE_SUSTITUIDO, IMPORTE_COBRADO, importe_pdte, REG, Status_factura) AS

SELECT C.CODIGO_RAPIDO,
       C.NOMBRE,
       C.RAZON_SOCIAL,
       C.TIPO_ENTIDAD,
       C.NIF,
       C.DIRECCION,
       C.FORMA_COBRO_PAGO,
       C.TIPO_CLIENTE,
       C.FECHA_BAJA,
       HC.ESTADO,
       HC.EMPRESA,
       HC.DOCUMENTO,
       HC.CONCEPTO,
       HC.FECHA_FACTURA,
       HC.FECHA_VENCIMIENTO,
       HC.FECHA_ASIENTO,
       HC.DOCUMENTO_VIVO,
       HC.IMPORTE,
       HC.IMPORTE_SUSTITUIDO,
       HC.IMPORTE_COBRADO,
       hc.importe_pdte,
       c.REG,
       decode( hc.importe_pdte,0,'Pagada','Pendiente') Status_factura
FROM v_HISTORICO_COBROS HC,
     (select CLIENTES.*,decode(clientes.ZONA,'0410','SCZ','0420','LPZ','0430','CBBA','0440','TJA','0450','ALTO','0451','ALTO','0460','SCR','0461','SCR','0470','BENI','0471','BENI','SIN REG') REG from clientes) C
WHERE HC.CODIGO_CLIENTE = C.CODIGO_RAPIDO
  AND C.FECHA_BAJA IS NULL
  AND HC.EMPRESA = C.CODIGO_EMPRESA
  AND HC.DOCUMENTO_VIVO in ('S','N')
  AND HC.STATUS_IMPAGADO IN ('N', 'S', 'D', 'P', 'A', 'F')
  AND HC.SITUACION_APUNTE = 'D'
  AND HC.EMPRESA = '004'
  and hc.IMPORTE_PDTE <>0 
  
  -- Revisar si corresponde este llevar como filtro
  AND NVL(HC.FACTORING, 'N') IN ('N', DECODE('S', 'S', 'A', 'N'), DECODE('N', 'S', 'F', 'N'))
  
  and IMPORTE_PDTE_DIVISA

  AND HC.CODIGO_CLIENTE IN (SELECT CODIGO_RAPIDO FROM CLIENTES WHERE EMPRESA = '004' AND FECHA_BAJA IS NULL)
  and hc.FECHA_FACTURA =to_Date('05/05/2025','DD/MM/YYYY')
