/* consulta para extraer datos de agentes y usuarios activos */
SELECT EMPRESA,ESTADO,PROVINCIA, CODIGO,NOMBRE,NIF,RESERVADOn01, USUARIO 
FROM AGENTES 
WHERE empresa='004' AND FECHA_BAJA IS NULL
ORDER BY PROVINCIA


/**** PARA EXTRAER USUSARIOS Y SUS DATOS*/
select USUARIO, descripcion,nif, email
  from USUARIOS 
 where FBAJA IS NULL AND perfil <> 'EMPLEADO' and GRUPO IS NOT NULL AND ESTADO='BOL'


/*** QUERY PAR AEXTRAER LOS DATOS COMBINADOS*/

SELECT EMPRESA,ESTADO,PROVINCIA, CODIGO,NOMBRE,NIF,RESERVADOn01, USUARIO, NOMBRE_USER, CI, EMAIL
FROM (SELECT AGENTES.*,(select descripcion from USUARIOS where USUARIO=AGENTES.USUARIO AND ESTADO='BOL') NOMBRE_USER, 
    (select NIF from USUARIOS where USUARIO=AGENTES.USUARIO AND ESTADO='BOL') CI, 
    (select EMAIL from USUARIOS where USUARIO=AGENTES.USUARIO AND ESTADO='BOL') EMAIL, 
    (select FBAJA from USUARIOS where USUARIO=AGENTES.USUARIO AND ESTADO='BOL') FBAJA 
    FROM AGENTES) AGENTES 
WHERE empresa='004'  AND ESTADO ='BOL' AND FBAJA IS NULL AND FECHA_BAJA IS NULL